/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package viggenere;

import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author Enrique
 */
public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        msj = new javax.swing.JTextField();
        Cifrar = new javax.swing.JButton();
        Descifrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        caja = new javax.swing.JTextArea();
        Clave = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();
        Fondo2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        msj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                msjActionPerformed(evt);
            }
        });
        getContentPane().add(msj, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 90, 200, 50));

        Cifrar.setText("Cifrar");
        Cifrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CifrarActionPerformed(evt);
            }
        });
        getContentPane().add(Cifrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 370, 100, 40));

        Descifrar.setText("Descifrar");
        Descifrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DescifrarActionPerformed(evt);
            }
        });
        getContentPane().add(Descifrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 370, 100, 40));

        caja.setColumns(20);
        caja.setRows(5);
        jScrollPane1.setViewportView(caja);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 430, 380, -1));

        Clave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClaveActionPerformed(evt);
            }
        });
        getContentPane().add(Clave, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 132, 44));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel1.setText("Cifrado Viggenere.");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, -1, 33));

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel2.setText("Ingresa la palabra o frase a cifrar");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, -1, -1));

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel3.setText("Ingrese la clave, esta debe ser más corta que la frase.");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, -1, 10));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/FonKw.jpg"))); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Fondo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fonCool.jpg"))); // NOI18N
        Fondo2.setText("jLabel4");
        getContentPane().add(Fondo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ClaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClaveActionPerformed
        
    }//GEN-LAST:event_ClaveActionPerformed

    private void CifrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CifrarActionPerformed
        Vigikawaii obj= new Vigikawaii(); 
        String textoclaro = msj.getText().toUpperCase();
        String clave = Clave.getText().toUpperCase();
        
        if (textoclaro.isEmpty() || clave.isEmpty()){
        JOptionPane.showMessageDialog(null,"Llene los campos para continuar");
        }else{
        Pattern p = Pattern.compile("[A-Za-z].*");
        Matcher txt = p.matcher(textoclaro);
        Matcher cla = p.matcher(clave);
               if(txt.matches()==true && cla.matches()==true) { 
                if(textoclaro.length() > clave.length()){
                    String resul = obj.encriptarTextoClaro(textoclaro.replace(" ", ""), clave.replace(" ", ""));
                    caja.setText(resul);
                }else{
                    JOptionPane.showMessageDialog(null,"La clave debe ser mas pequeña que el mensaje");  
                } 
               
            }else{
                JOptionPane.showMessageDialog(null,"No se aceptan caracteres especiales");  
            }
        }
    }//GEN-LAST:event_CifrarActionPerformed

    private void msjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_msjActionPerformed
            
    }//GEN-LAST:event_msjActionPerformed

    private void DescifrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DescifrarActionPerformed
        Vigikawaii obj= new Vigikawaii(); 
        String textoclaro = msj.getText().toUpperCase();
        String clave = Clave.getText().toUpperCase();
        
        if (textoclaro.isEmpty() || clave.isEmpty()){
        JOptionPane.showMessageDialog(null,"Llene los campos para continuar");
        }else{
        Pattern p = Pattern.compile("[A-Za-z].*");
        Matcher txt = p.matcher(textoclaro);
        Matcher cla = p.matcher(clave);
               if(txt.matches()==true && cla.matches()==true) { 
                if(textoclaro.length() > clave.length()){
                    String resul = obj.desencriptarTextoClaro(textoclaro.replace(" ", ""), clave.replace(" ", ""));
                    caja.setText(resul);
                }else{
                    JOptionPane.showMessageDialog(null,"La clave debe ser mas pequeña que el mensaje");  
                } 
               
            }else{
                JOptionPane.showMessageDialog(null,"No se aceptan caracteres especiales");  
            }
        }
    }//GEN-LAST:event_DescifrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
         try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
         
          java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cifrar;
    private javax.swing.JTextField Clave;
    private javax.swing.JButton Descifrar;
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel Fondo2;
    private javax.swing.JTextArea caja;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField msj;
    // End of variables declaration//GEN-END:variables
}
